# Explore the rate-allocator database

Read-only navigator over the SCD2 store defined in
[`src/rate_allocator/persistence/models.py`](../src/rate_allocator/persistence/models.py).

Point it at any SQLite or Postgres database by either:

- editing `DB_URL` in the next cell, or
- exporting `RATE_ALLOCATOR_DB_URL` before launching Jupyter.

Sections:

1. Tables and row counts
2. Change-batch audit log
3. Current institutions (live snapshot)
4. Tiers and constraints for a chosen institution
5. Regulatory rules
6. Time-travel snapshots via `load_institutions_from_db(..., as_of=...)`
7. Full SCD2 version history for a single tier
8. Switch to a different database without restarting the kernel

## 0. Setup

In [1]:
from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from sqlalchemy import inspect, select

from rate_allocator.adapters.db_loader import (
    load_institutions_from_db,
    load_regulatory_rules_from_db,
)
from rate_allocator.persistence import (
    DB_URL_ENV,
    create_db_engine,
    get_database_url,
    session_scope,
)
from rate_allocator.persistence.models import (
    ChangeBatch,
    ConstraintVersion,
    InstitutionVersion,
    RegulatoryRulesVersion,
    TierVersion,
)

REPO_ROOT = Path.cwd().resolve()
if REPO_ROOT.name == "notebooks":
    REPO_ROOT = REPO_ROOT.parent

# Override here to navigate a different DB; otherwise we honor the env var,
# falling back to the repo's local SQLite file.
DB_URL = os.environ.get(DB_URL_ENV) or f"sqlite:///{REPO_ROOT / 'data' / 'rates.db'}"
print("DB_URL:", DB_URL)

engine = create_db_engine(DB_URL)

DB_URL: sqlite:////Users/gera.ledesma/Desktop/Projects/rate-allocator/data/rates.db

## 1. Tables and row counts

In [2]:
def list_tables(engine):
    inspector = inspect(engine)
    rows = []
    with engine.connect() as conn:
        for table in sorted(inspector.get_table_names()):
            count = conn.exec_driver_sql(f"SELECT COUNT(*) FROM {table}").scalar_one()
            rows.append({"table": table, "rows": count})
    return pd.DataFrame(rows)

list_tables(engine)

                table  rows
0     alembic_version     1
1      change_batches     2
2       constraints_v     2
3      institutions_v     6
4  regulatory_rules_v     1
5             tiers_v    13

## 2. Change-batch audit log

Every ingest writes one row here. Source, actor, and note tell you why a
change happened; `applied_at` ties together the closed-old / inserted-new
rows produced by that batch.

In [3]:
with session_scope(engine) as session:
    batches = pd.read_sql(
        select(
            ChangeBatch.change_id,
            ChangeBatch.applied_at,
            ChangeBatch.source,
            ChangeBatch.actor,
            ChangeBatch.note,
        ).order_by(ChangeBatch.applied_at.desc()),
        session.connection(),
    )
batches

,change_id,applied_at,source,actor,note
0,4ff6f604-601a-487f-aa96-462da73234cc,2026-05-09 01:46:28.099543,yaml:data/regulatory_rules.mx.yaml,None,MX rules
1,cf7bdd92-926d-499d-b919-417e420a15ef,2026-05-09 01:46:23.826005,yaml:data/sample1.yaml,None,local demo

## 3. Current institutions

`effective_to IS NULL` is the live snapshot. The `current_tiers` count is
how many tiers each institution has right now.

In [4]:
with session_scope(engine) as session:
    institutions = pd.read_sql(
        select(
            InstitutionVersion.business_key,
            InstitutionVersion.name,
            InstitutionVersion.institution_type,
            InstitutionVersion.protection_limit,
            InstitutionVersion.effective_from,
            InstitutionVersion.change_id,
        ).where(InstitutionVersion.effective_to.is_(None)),
        session.connection(),
    )
    tiers = pd.read_sql(
        select(
            TierVersion.institution_business_key,
            TierVersion.tier_index,
        ).where(TierVersion.effective_to.is_(None)),
        session.connection(),
    )

tier_counts = (
    tiers.groupby("institution_business_key")
    .size()
    .rename("current_tiers")
    .reset_index()
)
institutions.merge(
    tier_counts,
    left_on="business_key",
    right_on="institution_business_key",
    how="left",
).drop(columns=["institution_business_key"]).fillna({"current_tiers": 0})

,business_key,name,institution_type,protection_limit,effective_from,change_id,current_tiers
0,Mifel,Mifel,banco,None,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef,3
1,Nu,Nu,sofipo,None,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef,2
2,OpenBank,OpenBank,banco,None,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef,3
3,PlataAhorroPlus,PlataAhorroPlus,banco,None,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef,1
4,Revolut,Revolut,banco,None,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef,3
5,cetes28,cetes28,none,None,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef,1

## 4. Tiers and constraints for one institution

Edit `INSTITUTION` to drill into a specific institution. Tiers are ordered
by `tier_index`; constraints are joined in by tier and ordered by
`constraint_position`. `limit_mxn = NaN` represents the unbounded `inf`
tier (sentinel-free in the DB).

In [5]:
INSTITUTION = "Nu"

with session_scope(engine) as session:
    tiers_df = pd.read_sql(
        select(
            TierVersion.tier_index,
            TierVersion.limit_mxn,
            TierVersion.rate,
            TierVersion.effective_from,
            TierVersion.change_id,
        )
        .where(TierVersion.institution_business_key == INSTITUTION)
        .where(TierVersion.effective_to.is_(None))
        .order_by(TierVersion.tier_index),
        session.connection(),
    )
    constraints_df = pd.read_sql(
        select(
            ConstraintVersion.tier_index,
            ConstraintVersion.constraint_position,
            ConstraintVersion.type,
            ConstraintVersion.cost,
            ConstraintVersion.benefit,
            ConstraintVersion.condition_value,
            ConstraintVersion.active,
        )
        .where(ConstraintVersion.institution_business_key == INSTITUTION)
        .where(ConstraintVersion.effective_to.is_(None))
        .order_by(ConstraintVersion.tier_index, ConstraintVersion.constraint_position),
        session.connection(),
    )

print(f"Tiers for {INSTITUTION!r}:")
display(tiers_df)
print(f"\nConstraints for {INSTITUTION!r}:")
display(constraints_df)

Tiers for 'Nu':

,tier_index,limit_mxn,rate,effective_from,change_id
0,0,25000.0,0.1300,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef
1,1,NaN,0.0675,2026-05-09 01:46:23.826005,cf7bdd92-926d-499d-b919-417e420a15ef

Constraints for 'Nu':

,tier_index,constraint_position,type,cost,benefit,condition_value,active
0,0,0,monthly_expense,1.0,high_rate_tier,1.0,True

## 5. Regulatory rules

The full payload is stored as JSON so the schema doesn't have to grow with
every new rule field. The current row per country has `effective_to IS NULL`.

In [6]:
with session_scope(engine) as session:
    rules_df = pd.read_sql(
        select(
            RegulatoryRulesVersion.country,
            RegulatoryRulesVersion.payload,
            RegulatoryRulesVersion.effective_from,
            RegulatoryRulesVersion.effective_to,
            RegulatoryRulesVersion.change_id,
        ).order_by(
            RegulatoryRulesVersion.country,
            RegulatoryRulesVersion.effective_from.desc(),
        ),
        session.connection(),
    )
    current_rules = load_regulatory_rules_from_db(session, country="MX")

print("Current MX rules dataclass:", current_rules)
rules_df

Current MX rules dataclass: RegulatoryRules(country='MX', effective_from='2026-01-01', bank_insurance_limit_mxn=3300000.0, sofipo_insurance_limit_mxn=208000.0, bank_isr_withholding_rate_annual=0.009, real_interest_isr_rate_annual=0.009, inflation_proxy_annual=0.0421, sofipo_exempt_balance_limit_mxn=213973.0, sofipo_excess_isr_rate_annual=0.009)

,country,payload,effective_from,effective_to,change_id
0,MX,"{'country': 'MX', 'effective_from': '2026-01-0...",2026-05-09 01:46:28.099543,None,4ff6f604-601a-487f-aa96-462da73234cc

## 6. Time travel

`load_institutions_from_db(..., as_of=...)` returns the snapshot effective
at the given timestamp. With no argument it returns the current snapshot.
This is the same code path the allocator uses, so you can backtest
historical rate changes through `allocate(...)` without code changes.

In [7]:
with session_scope(engine) as session:
    current = load_institutions_from_db(session)

print(f"Current snapshot: {len(current)} institutions")
for inst in current:
    print(f"  {inst.name:<20} type={inst.institution_type:<7} tiers={len(inst.tiers)}")

Current snapshot: 6 institutions
  Mifel                type=banco   tiers=3
  Nu                   type=sofipo  tiers=2
  OpenBank             type=banco   tiers=3
  PlataAhorroPlus      type=banco   tiers=1
  Revolut              type=banco   tiers=3
  cetes28              type=none    tiers=1

In [8]:
# Pick a historical point. By default we use the earliest known applied_at,
# i.e. just after the very first ingest, so you'll see the original rates.
with session_scope(engine) as session:
    first_applied_at = session.execute(
        select(ChangeBatch.applied_at).order_by(ChangeBatch.applied_at.asc()).limit(1)
    ).scalar_one_or_none()

if first_applied_at is None:
    print("No batches recorded yet; ingest something first.")
else:
    as_of = first_applied_at
    with session_scope(engine) as session:
        historical = load_institutions_from_db(session, as_of=as_of)
    print(f"Snapshot as_of {as_of.isoformat()}: {len(historical)} institutions")
    for inst in historical:
        print(f"  {inst.name:<20} tiers={len(inst.tiers)}  first_rate={inst.tiers[0].rate:.4f}")

Snapshot as_of 2026-05-09T01:46:23.826005: 6 institutions
  Mifel                tiers=3  first_rate=0.0000
  Nu                   tiers=2  first_rate=0.1300
  OpenBank             tiers=3  first_rate=0.1300
  PlataAhorroPlus      tiers=1  first_rate=0.1200
  Revolut              tiers=3  first_rate=0.2500
  cetes28              tiers=1  first_rate=0.0655

## 7. Full version history for one tier

This shows every version SCD2 has ever stored for the chosen
`(institution, tier_index)`. Closed rows have a non-null `effective_to`;
the active row has `effective_to = NaT`.

In [9]:
HISTORY_INSTITUTION = "Nu"
HISTORY_TIER_INDEX = 0

with session_scope(engine) as session:
    history = pd.read_sql(
        select(
            TierVersion.tier_row_id,
            TierVersion.tier_index,
            TierVersion.limit_mxn,
            TierVersion.rate,
            TierVersion.effective_from,
            TierVersion.effective_to,
            TierVersion.change_id,
        )
        .where(TierVersion.institution_business_key == HISTORY_INSTITUTION)
        .where(TierVersion.tier_index == HISTORY_TIER_INDEX)
        .order_by(TierVersion.effective_from),
        session.connection(),
    )

print(f"Versions for {HISTORY_INSTITUTION!r} tier {HISTORY_TIER_INDEX}: {len(history)}")
history

Versions for 'Nu' tier 0: 1

,tier_row_id,tier_index,limit_mxn,rate,effective_from,effective_to,change_id
0,2,0,25000.0,0.13,2026-05-09 01:46:23.826005,None,cf7bdd92-926d-499d-b919-417e420a15ef

## 8. Switch to another database

To navigate a different store without restarting, build a fresh engine
against a different URL. SQLite files are easy targets (one per file);
Postgres works the same way with a `postgresql+psycopg://...` URL.

In [10]:
def use_database(url: str):
    """Rebind the notebook's ``engine`` to a different DB URL."""
    global engine, DB_URL
    DB_URL = url
    engine = create_db_engine(url)
    print("Now connected to:", url)
    return list_tables(engine)


# Examples (uncomment one):
# use_database(f"sqlite:///{REPO_ROOT / 'data' / 'rates.db'}")
# use_database("sqlite:///" + str(REPO_ROOT / "data" / "another.db"))
# use_database("postgresql+psycopg://user:pwd@host:5432/rates")

list_tables(engine)

                table  rows
0     alembic_version     1
1      change_batches     2
2       constraints_v     2
3      institutions_v     6
4  regulatory_rules_v     1
5             tiers_v    13